/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigzhao_cbtcrack_Hack */

#ifndef _Included_com_bigzhao_cbtcrack_Hack
#define _Included_com_bigzhao_cbtcrack_Hack
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_bigzhao_cbtcrack_Hack
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bigzhao_cbtcrack_Hack_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_bigzhao_cbtcrack_Hack
 * Method:    readFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bigzhao_cbtcrack_Hack_readFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
