/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigzhao_jianrmagicbox_CppInterface */

#ifndef _Included_com_bigzhao_jianrmagicbox_CppInterface
#define _Included_com_bigzhao_jianrmagicbox_CppInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bigzhao_jianrmagicbox_CppInterface
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bigzhao_jianrmagicbox_CppInterface_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
